repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: detect-private-key

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: go fmt ./...
        language: system
        types: [go]
        pass_filenames: false
        always_run: true

      - id: go-imports
        name: goimports
        entry: goimports -w .
        language: system
        types: [go]
        pass_filenames: false
        always_run: true

      - id: go-unit-tests
        name: go test
        entry: go test ./...
        language: system
        types: [go]
        pass_filenames: false
        always_run: true

      - id: go-build
        name: go build
        entry: go build ./...
        language: system
        types: [go]
        pass_filenames: false
        always_run: true

      - id: go-mod-tidy
        name: go mod tidy
        entry: go mod tidy
        language: system
        types: [go]
        pass_filenames: false
        always_run: true

      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run
        language: system
        types: [go]
        pass_filenames: false
        always_run: true

      - id: govulncheck
        name: govulncheck
        entry: govulncheck ./...
        language: system
        types: [go]
        pass_filenames: false
        always_run: true
