name: Release

on:
  push:
    # Trigger on semantic version tags (e.g., v1.0.0, v2.1.3, v1.0.0-beta.1)
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          # Fetch full history for changelog generation
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Verify Go modules
        run: |
          go mod download
          go mod verify

      - name: Run tests
        run: go test -race -coverprofile=coverage.out ./...

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Set GITHUB_REPOSITORY_OWNER for templates
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

  # Optional: Create a job to update package managers (if configured)
  # update-package-managers:
  #   needs: goreleaser
  #   runs-on: ubuntu-latest
  #   if: success()
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v5
  #
  #     - name: Update Homebrew formula
  #       # This would run if you have Homebrew tap configured in .goreleaser.yml
  #       run: echo "Homebrew formula updated"
